language: python
python:
  - 3.5
rvm:
  - 2.0.0

if: type = pull_request OR tag IS present OR branch =~ /^(master|release-[0-9_]+)$/

# Handle git submodules manually
git:
  submodules: false

services:
  - docker

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - openssl aes-256-cbc -K $encrypted_c158cd588669_key -iv $encrypted_c158cd588669_iv -in keystore.p12.enc -out keystore.p12 -d

script:
  - export QFIELD_SDK_VERSION=$(awk -F "=" '/osgeo4a_version/{print $2}' sdk.conf)
  - ./scripts/ci/docker_pull.sh
  - pip install transifex-client
  - ./scripts/ci/pull_translations.sh
  - ./scripts/ci/travis_build.sh
  - ./scripts/upload-artifacts.sh

jobs:
  include:
    - stage: prepare-release
      if: tag IS present AND branch =~ /^(master|release-[0-9_]+)$/
      name: "ğŸ‘· Prepare release"
      script:
        - pip install transifex-client
        - ./scripts/prepare-release.sh

    - stage: test
      name: "ğŸ³ Testing"
      script:
        - ./test/test_version_number.sh
        - echo "travis_fold:start:build\n$(tput bold)Build QField $(tput sgr0)"
        - ./scripts/ci/pull_translations.sh
        - docker-compose -f .docker/testing/docker-compose-travis.yml run qgis /usr/src/.docker/testing/build-test.sh

    - stage: test
      name: "ğŸ“± Build armv7"
      env:
        - ARCH=armv7
    - stage: test
      name: "ğŸ“± Build arm64-v8a"
      env:
        - ARCH=arm64_v8a
    - stage: test
      name: "ğŸ“± Build x86"
      env:
        - ARCH=x86
    - stage: test
      name: "ğŸ“± Build x86_64"
      env:
        - ARCH=x86_64

    - stage: deploy
      name: "ğŸº Deploy"
      script:
        - pip install pyopenssl
        - pip install google-api-python-client
        - pip install oauth2client
        - pip install pygithub
        - ./scripts/deploy.sh # Upload pull request apk artifacts if possible

    # TRANSLATIONS
    - stage: deploy
      name: "ğŸŒ Push Translations"
      if: branch =~ /^(master|release-[0-9_]+)$/ AND type != pull_request
      addons:
        apt:
          packages:
          - qttools5-dev-tools
      install:
        - pip install pygithub transifex-client
      script: ./scripts/ci/update-translations.sh

