language: python
python:
  - 3.5
rvm:
  - 2.0.0

# Handle git submodules manually
git:
  submodules: false

services:
  - docker

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - openssl aes-256-cbc -K $encrypted_c158cd588669_key -iv $encrypted_c158cd588669_iv -in keystore.p12.enc -out keystore.p12 -d

script:
  - export QFIELD_SDK_VERSION=$(cat sdk.conf | cut -d= -f2)
  - ./scripts/ci/docker_pull.sh
  - ./scripts/ci/pull_translations.sh
  - ./scripts/ci/travis_build.sh
  - ./scripts/upload-artifacts.sh

jobs:
  allow_failures:
    - name: "üç≥ Testing"
  include:
    - stage: test
      name: "üç≥ Testing"
      script:
        - echo "travis_fold:start:build\n$(tput bold)Build QField $(tput sgr0)"
        - ./scripts/ci/pull_translations.sh
        - docker-compose -f .docker/testing/docker-compose-travis.yml run qgis /usr/src/.docker/testing/build-test.sh
      if: type = pull_request OR tag IS present OR branch = master


    - stage: test
      name: "üì± Build armv7"
      env:
        - ARCH=armv7
        - ARCH_BUILD_NUMBER=1
      if: type = pull_request OR tag IS present OR branch = master
    - stage: test
      name: "üì± Build arm64-v8a"
      env:
        - ARCH=arm64_v8a
        - ARCH_BUILD_NUMBER=2
      if: type = pull_request OR tag IS present OR branch = master
    - stage: test
      name: "üì± Build x86"
      env:
        - ARCH=x86
        - ARCH_BUILD_NUMBER=3
      if: type = pull_request OR tag IS present OR branch = master
    - stage: test
      name: "üì± Build x86_64"
      env:
        - ARCH=x86_64
        - ARCH_BUILD_NUMBER=4
      if: type = pull_request OR tag IS present OR branch = master


    - stage: deploy
      name: "üç∫ Deploy"
      if: type = pull_request OR tag IS present OR branch = master
      script:
        - pip install pyopenssl
        - pip install google-api-python-client
        - pip install oauth2client
        - pip install pygithub
        - ./scripts/deploy.sh # Upload pull request apk artifacts if possible
    - stage: deploy
      name: "üåç Translations"
      if: branch = master AND type != pull_request
      addons:
        apt:
          packages:
          - qttools5-dev-tools
      install:
        - pip install -r requirements.txt
        - pip install pygithub
      script: ./scripts/ci/update-translations.sh

matrix:
  fast_finish: true 
