blank_issues_enabled: false

contact_links:
  - name: Enhancement proposals/feature requests for the QField ecosystem
    url: https://ideas.qfield.org
    about: >
      Add your suggestion how to improve QField, QFieldSync, QFieldCloud or QFieldCloud SDK at https://support.qfield.cloud/ .

  - name: Support for your QFieldCloud account at [app.qfield.cloud](https://app.qfield.cloud)
    url: https://support.qfield.cloud
    about: >
      Open a ticket at our support platform for app.qfield.cloud users at https://support.qfield.cloud/ .

  - name: Bug report for QFieldSync
    url: https://github.com/opengisch/QFieldSync/issues
    about: >
      Check if your issue was already reported and if not, then create a new issue at the QFieldSync repository.

  - name: Bug report for QFieldCloud SDK
    url: https://github.com/opengisch/QFieldCloud-sdk-python/issues
    about: >
      Check if your issue was already reported and if not, then create a new issue at the QFieldCloud Python SDK repository.

  - name: Commercial and community support
    url: https://docs.qfield.org/get-started/support/
    about: >
      Check how to get commercial or community support for your QField ecosystem questions.

  - name: Missing documentation (QField, QFieldSync, QFieldCloud, QFieldCloud SDK)
    url: https://github.com/opengisch/qfield-docs/issues
    about: >
      Suggest improvements or report documentation errors regarding https://docs.qfield.org .

  - name: QField plugin issue
    url: https://github.com/topics/qfield-plugin
    about: >
      If the issue concerns a third party plugin (downloaded within the QField plugin manager)
      then it can't be fixed by the QField core team.
      Please raise your issue in the dedicated bug tracker for that specific plugin.
