name: Translations

on: [push]

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Requirements
        run: |
          sudo apt update && sudo apt install qt5-default qttools5-dev-tools
          sudo pip install wheel
          sudo pip install pygithub transifex-client
          ./scripts/ci/env_gh.sh

      - name: "ğŸŒ Push Translations"
        run: ./scripts/ci/update-translations.sh
